{
    "0000": "General Success",
    "1000": "User logged in successfully",
    "1001": "User account creation successful",    
    "2000": "User can deposit exactly 100 Krone per day",
    "2001": "User can deposit only once per day",
    "2002": "User can deposit a maximum of 500 Krone",
    "2003": "User can withdraw only from available deposit balance",
    "2004": "Provided amount cannot be negative",
    "9950": "UserID or Password is incorrect",
    "9951": "Your account is inactive",
    "9952": "Your account is blocked",
    "9953": "This User ID is taken",
    "9954": "You have an account with this email",
    "9989": "Invalid request",
    "9990": "Invalid login credentials",
    "9991": "Record delete failed",
    "9992": "Record update failed",
    "9993": "Record insertion failed",
    "9994": "Error in OTP generation",
    "9995": "Token expired",
    "9996": "Invalid User Token",
    "9997": "No data found",
    "9998": "Missing mandatory fields data",
    "9999": "An unexpected error occurred on the server side"
}
